VERSION: "inference_demo"
TRAINING_TYPE: 'coarse-fine'

FINE_MODEL_PATH: "checkpoints_dir/hilab_test_stage" # The path of the downloaded checkpoint directory.
CHECK_POINT_NAME: "200_checkpoint.pth"
COARSE_MODEL_PATH: "checkpoints_dir/hilab_test_stage" # The path of the downloaded checkpoint directory.
COARSE_CHECK_POINT_NAME: "coarse_checkpoint.pth"

DATASET:
  BASE_DIR: './' # The path of the current project datasets directory.

VAL:
  IS_CROP: False
  TTA: False

INFERENCE:
  IS_OVERWRITE_PREDICT_MASK: True