BASE: ['train_small_segnet_fine_stage.yaml']

FINETUNE: True

DATASET:
  DATASET_NAME: 'fake_MR_PET_fine_fintune'
  FINE:
    # SPLIT_PREPROCESS_PATH: [
    #   'processed_data/fine/big_segnet/ct300',
    #   'processed_data/fine/big_segnet/MR_lld_stage3',
    #   'processed_data/fine/big_segnet/MR_amos_stage3',
    # ]
    PROPRECESS_PATH: "processed_data/fine/small_segnet/whm_stage3_mr_pet_01"

TRAIN:
  EPOCHS: 200
  WARMUP_EPOCHS: 10
  BASE_LR: 1e-6 # 2e-4
  MIN_LR: 5e-7 # 5e-6

